BEGIN;

-- categories
INSERT INTO categories (name)
VALUES ('Elektronik'),
       ('Computer'),
       ('Peripheriegeräte'),
       ('Speicher'),
       ('Netzwerk'),
       ('Audio'),
       ('Foto & Video'),
       ('Gaming'),
       ('Haushaltsgeräte'),
       ('Werkzeuge'),
       ('Bürobedarf'),
       ('Smart Home');

-- suppliers
INSERT INTO suppliers (name, email, phone)
VALUES ('TechnoHaus GmbH', 'vertrieb@technohaus.de', '+49 684 214 1409'),
       ('Berliner Elektronik AG', 'vertrieb@berliner.de', '+49 789 381 5012'),
       ('München Digital GmbH', 'vertrieb@muenchen.de', '+49 258 242 2679'),
       ('RheinTech Handels GmbH', 'vertrieb@rheintech.de', '+49 722 858 9935'),
       ('Hanse IT Distribution GmbH', 'vertrieb@hanse.de', '+49 119 704 7912'),
       ('Schwarzwald Komponenten GmbH', 'vertrieb@schwarzwald.de', '+49 62 130 2535'),
       ('Nordlicht Systeme GmbH', 'vertrieb@nordlicht.de', '+49 253 338 9279'),
       ('Frankfurt Hardware GmbH', 'vertrieb@frankfurt.de', '+49 646 127 4257'),
       ('Sachsen Computer GmbH', 'vertrieb@sachsen.de', '+49 763 765 9928'),
       ('Alpen Peripherie GmbH', 'vertrieb@alpen.de', '+49 459 325 8359'),
       ('Elbe Logistik & Technik GmbH', 'vertrieb@elbe.de', '+49 633 384 1106'),
       ('Westfalen Elektro GmbH', 'vertrieb@westfalen.de', '+49 807 925 3615'),
       ('Donau Distribution GmbH', 'vertrieb@donau.de', '+49 744 532 6574'),
       ('Bavaria Tech Supply GmbH', 'vertrieb@bavaria.de', '+49 314 259 4527'),
       ('Kiel Marine Electronics GmbH', 'vertrieb@kiel.de', '+49 811 444 2674'),
       ('Ruhr Digital GmbH', 'vertrieb@ruhr.de', '+49 124 489 2584'),
       ('Leipzig Netzwerk GmbH', 'vertrieb@leipzig.de', '+49 397 967 6635'),
       ('Stuttgart Präzision GmbH', 'vertrieb@stuttgart.de', '+49 648 370 1711'),
       ('Hamburger Speicher GmbH', 'vertrieb@hamburger.de', '+49 777 570 9785'),
       ('Köln Media Systeme GmbH', 'vertrieb@koeln.de', '+49 157 487 2291');

-- warehouses
INSERT INTO warehouses (name, location)
VALUES ('Zentrallager Berlin', 'Berlin - Gewerbegebiet Marzahn'),
       ('Lager Süd München', 'München - Logistikpark Aschheim'),
       ('Lager West Köln', 'Köln - Industriepark Nord'),
       ('Lager Frankfurt', 'Frankfurt am Main - Cargo City Süd'),
       ('Hafenlager Hamburg', 'Hamburg - HafenCity Speicherstadt'),
       ('Lager Stuttgart', 'Stuttgart - Gewerbepark Vaihingen'),
       ('Lager Leipzig', 'Leipzig - GVZ Leipzig-Nord'),
       ('Lager Dortmund', 'Dortmund - Westfalenhütte Logistik'),
       ('Lager Hannover', 'Hannover - Güterverkehrszentrum'),
       ('Lager Nürnberg', 'Nürnberg - Hafen Industriegebiet');

-- products (235 registros)
INSERT INTO products (sku, name, description, price, stock, category_id, supplier_id)
VALUES ('B-00001', 'Orbit Bürostuhl S', 'Bürostuhl der Marke Orbit, Modell S', 1083.06, 30,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('H-00002', 'Delphi Luftreiniger Air', 'Luftreiniger der Marke Delphi, Modell Air', 922.04, 223,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('G-00003', 'Orbit Gaming-Tastatur Eco', 'Gaming-Tastatur der Marke Orbit, Modell Eco', 18.65, 180,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('H-00004', 'Nordika Staubsauger Neo', 'Staubsauger der Marke Nordika, Modell Neo', 1156.11, 382,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('SH-00005', 'Nordika Smart-Thermostat X', 'Smart-Thermostat der Marke Nordika, Modell X', 336.27, 38,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('S-00006', 'Delphi RAM-Modul Lite', 'RAM-Modul der Marke Delphi, Modell Lite', 522.65, 309,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('P-00007', 'Bergmann Drucker Pro', 'Drucker der Marke Bergmann, Modell Pro', 1241.03, 276,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('P-00008', 'Orbit Grafiktablett 4K', 'Grafiktablett der Marke Orbit, Modell 4K', 1818.27, 401,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('S-00009', 'Zentra SD-Karte Neo', 'SD-Karte der Marke Zentra, Modell Neo', 1868.46, 413,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('C-00010', 'Kronos Laptop S', 'Laptop der Marke Kronos, Modell S', 1845.83, 390,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('C-00011', 'Nordika Mini-PC 2000', 'Mini-PC der Marke Nordika, Modell 2000', 1811.04, 472,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('P-00012', 'Kestrel Tastatur X', 'Tastatur der Marke Kestrel, Modell X', 1027.46, 370,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('C-00013', 'Bergmann Workstation Max', 'Workstation der Marke Bergmann, Modell Max', 1391.90, 417,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('A-00014', 'Wolkenstein Bluetooth-Empfänger Compact',
        'Bluetooth-Empfänger der Marke Wolkenstein, Modell Compact', 1461.10, 233,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('N-00015', 'Orbit Netzwerkkabel Air', 'Netzwerkkabel der Marke Orbit, Modell Air', 1274.63, 376,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('FV-00016', 'Kronos Systemkamera 2000', 'Systemkamera der Marke Kronos, Modell 2000', 886.20, 285,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('S-00017', 'Adler SD-Karte 2000', 'SD-Karte der Marke Adler, Modell 2000', 22.30, 418,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('E-00018', 'Zentra Spannungswandler 4K', 'Spannungswandler der Marke Zentra, Modell 4K', 1779.18, 331,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('SH-00019', 'Zentra Bewegungsmelder Lite', 'Bewegungsmelder der Marke Zentra, Modell Lite', 1893.22, 223,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('P-00020', 'Kestrel Drucker Air', 'Drucker der Marke Kestrel, Modell Air', 1636.74, 281,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('FV-00021', 'Zentra Ringlicht Air', 'Ringlicht der Marke Zentra, Modell Air', 475.15, 326,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('W-00022', 'Delphi Werkzeugset Pro', 'Werkzeugset der Marke Delphi, Modell Pro', 984.70, 97,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('E-00023', 'Wolkenstein USB-Hub Eco', 'USB-Hub der Marke Wolkenstein, Modell Eco', 1008.32, 497,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('P-00024', 'Falkon Webcam X', 'Webcam der Marke Falkon, Modell X', 1021.88, 71,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Schwarzwald Komponenten GmbH')),
       ('A-00025', 'Vaillux Kopfhörer Ultra', 'Kopfhörer der Marke Vaillux, Modell Ultra', 1154.14, 261,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('P-00026', 'Bergmann Tastatur HD', 'Tastatur der Marke Bergmann, Modell HD', 822.83, 216,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('S-00027', 'Falkon SSD NVMe Ultra', 'SSD NVMe der Marke Falkon, Modell Ultra', 234.27, 455,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('E-00028', 'Aurus Netzteil HD', 'Netzteil der Marke Aurus, Modell HD', 438.57, 148,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('P-00029', 'Kestrel Tastatur Air', 'Tastatur der Marke Kestrel, Modell Air', 777.45, 48,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('G-00030', 'Kronos Gaming-Maus Pro', 'Gaming-Maus der Marke Kronos, Modell Pro', 1628.01, 391,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('H-00031', 'Adler Luftreiniger S', 'Luftreiniger der Marke Adler, Modell S', 1172.50, 470,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('H-00032', 'Falkon Kaffeemaschine Lite', 'Kaffeemaschine der Marke Falkon, Modell Lite', 903.24, 58,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Schwarzwald Komponenten GmbH')),
       ('C-00033', 'Zentra Mainboard 2000', 'Mainboard der Marke Zentra, Modell 2000', 1657.71, 216,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('G-00034', 'Adler Headset Air', 'Headset der Marke Adler, Modell Air', 772.26, 84,
        (SELECT id FROM categories WHERE name = 'Gaming'), (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('N-00035', 'Wolkenstein WLAN-Repeater 4K', 'WLAN-Repeater der Marke Wolkenstein, Modell 4K', 299.84, 476,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('B-00036', 'Wolkenstein Bürostuhl 4K', 'Bürostuhl der Marke Wolkenstein, Modell 4K', 195.20, 390,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('FV-00037', 'Vaillux Speicherkarten-Leser 2000', 'Speicherkarten-Leser der Marke Vaillux, Modell 2000', 888.80,
        31, (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('W-00038', 'Bergmann Akkuschrauber S', 'Akkuschrauber der Marke Bergmann, Modell S', 1675.11, 124,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('E-00039', 'Nordika Multimeter X', 'Multimeter der Marke Nordika, Modell X', 1416.65, 275,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('G-00040', 'Zentra Gaming-Tastatur Air', 'Gaming-Tastatur der Marke Zentra, Modell Air', 745.16, 456,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('G-00041', 'Kestrel Headset Pro', 'Headset der Marke Kestrel, Modell Pro', 743.02, 342,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('H-00042', 'Nordika Luftreiniger Ultra', 'Luftreiniger der Marke Nordika, Modell Ultra', 340.66, 267,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('S-00043', 'Orbit SSD SATA Lite', 'SSD SATA der Marke Orbit, Modell Lite', 1278.00, 153,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('P-00044', 'Wolkenstein Tastatur Neo', 'Tastatur der Marke Wolkenstein, Modell Neo', 901.56, 401,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('C-00045', 'Nordika Laptop Eco', 'Laptop der Marke Nordika, Modell Eco', 13.64, 369,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00046', 'Aurus Kaffeemaschine Air', 'Kaffeemaschine der Marke Aurus, Modell Air', 66.19, 126,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('A-00047', 'Delphi Kopfhörer Air', 'Kopfhörer der Marke Delphi, Modell Air', 1025.98, 368,
        (SELECT id FROM categories WHERE name = 'Audio'), (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('FV-00048', 'Kestrel Stativ Neo', 'Stativ der Marke Kestrel, Modell Neo', 1549.08, 456,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('W-00049', 'Bergmann Werkzeugset X', 'Werkzeugset der Marke Bergmann, Modell X', 1369.52, 250,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('W-00050', 'Aurus Bohrmaschine Eco', 'Bohrmaschine der Marke Aurus, Modell Eco', 1617.08, 93,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('FV-00051', 'Kronos Speicherkarten-Leser X', 'Speicherkarten-Leser der Marke Kronos, Modell X', 128.99, 208,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('FV-00052', 'Bergmann Objektiv Eco', 'Objektiv der Marke Bergmann, Modell Eco', 259.71, 237,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('SH-00053', 'Nordika Türklingel S', 'Türklingel der Marke Nordika, Modell S', 1571.07, 36,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('SH-00054', 'Aurus Türklingel Lite', 'Türklingel der Marke Aurus, Modell Lite', 1506.76, 304,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('SH-00055', 'Orbit LED-Lampe 4K', 'LED-Lampe der Marke Orbit, Modell 4K', 617.17, 128,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('E-00056', 'Zentra Multimeter 4K', 'Multimeter der Marke Zentra, Modell 4K', 1113.24, 459,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('N-00057', 'Nordika Router Pro', 'Router der Marke Nordika, Modell Pro', 590.57, 460,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('C-00058', 'Adler Desktop-PC 2000', 'Desktop-PC der Marke Adler, Modell 2000', 1159.37, 78,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('W-00059', 'Delphi Winkelschleifer Neo', 'Winkelschleifer der Marke Delphi, Modell Neo', 542.79, 51,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('B-00060', 'Wolkenstein Whiteboard S', 'Whiteboard der Marke Wolkenstein, Modell S', 168.62, 127,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('G-00061', 'Bergmann Controller HD', 'Controller der Marke Bergmann, Modell HD', 818.22, 443,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('S-00062', 'Nordika SSD NVMe Max', 'SSD NVMe der Marke Nordika, Modell Max', 1133.01, 345,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('S-00063', 'Nordika NAS-Gehäuse HD', 'NAS-Gehäuse der Marke Nordika, Modell HD', 1860.79, 82,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('SH-00064', 'Falkon Smart-Steckdose Ultra', 'Smart-Steckdose der Marke Falkon, Modell Ultra', 224.60, 115,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('A-00065', 'Kestrel Soundbar Eco', 'Soundbar der Marke Kestrel, Modell Eco', 1285.45, 261,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('SH-00066', 'Kronos Türklingel Compact', 'Türklingel der Marke Kronos, Modell Compact', 1084.16, 147,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('FV-00067', 'Delphi Stativ Ultra', 'Stativ der Marke Delphi, Modell Ultra', 1578.52, 280,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('E-00068', 'Delphi USB-Hub Compact', 'USB-Hub der Marke Delphi, Modell Compact', 1790.11, 348,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('H-00069', 'Kronos Luftreiniger Neo', 'Luftreiniger der Marke Kronos, Modell Neo', 515.17, 436,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('G-00070', 'Orbit Gaming-Maus Ultra', 'Gaming-Maus der Marke Orbit, Modell Ultra', 1719.00, 299,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('N-00071', 'Falkon Access Point X', 'Access Point der Marke Falkon, Modell X', 1552.07, 235,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('P-00072', 'Bergmann Scanner Air', 'Scanner der Marke Bergmann, Modell Air', 1612.81, 85,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('E-00073', 'Vaillux Powerbank Ultra', 'Powerbank der Marke Vaillux, Modell Ultra', 513.93, 108,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('SH-00074', 'Kestrel Überwachungskamera S', 'Überwachungskamera der Marke Kestrel, Modell S', 69.24, 147,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('C-00075', 'Delphi Prozessor Air', 'Prozessor der Marke Delphi, Modell Air', 1388.16, 102,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('H-00076', 'Falkon Kaffeemaschine Compact', 'Kaffeemaschine der Marke Falkon, Modell Compact', 46.05, 78,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('E-00077', 'Falkon Ladegerät Lite', 'Ladegerät der Marke Falkon, Modell Lite', 881.87, 138,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('N-00078', 'Aurus Modem Max', 'Modem der Marke Aurus, Modell Max', 1135.91, 176,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('W-00079', 'Bergmann Lötkolben S', 'Lötkolben der Marke Bergmann, Modell S', 426.65, 354,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('H-00080', 'Vaillux Mixer Max', 'Mixer der Marke Vaillux, Modell Max', 964.52, 174,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('A-00081', 'Wolkenstein Soundbar Neo', 'Soundbar der Marke Wolkenstein, Modell Neo', 1245.88, 238,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('A-00082', 'Zentra Lautsprecher 2000', 'Lautsprecher der Marke Zentra, Modell 2000', 592.51, 209,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('FV-00083', 'Vaillux Gimbal Plus', 'Gimbal der Marke Vaillux, Modell Plus', 1696.66, 41,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('A-00084', 'Falkon Mikrofon Ultra', 'Mikrofon der Marke Falkon, Modell Ultra', 1265.21, 194,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('E-00085', 'Aurus Powerbank X', 'Powerbank der Marke Aurus, Modell X', 1561.94, 412,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('N-00086', 'Bergmann Switch Plus', 'Switch der Marke Bergmann, Modell Plus', 1483.09, 452,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('P-00087', 'Kronos Maus Plus', 'Maus der Marke Kronos, Modell Plus', 1521.82, 55,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('H-00088', 'Zentra Mixer Compact', 'Mixer der Marke Zentra, Modell Compact', 1301.78, 412,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('C-00089', 'Vaillux Gehäuse Max', 'Gehäuse der Marke Vaillux, Modell Max', 980.03, 142,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('W-00090', 'Kestrel Akkuschrauber Neo', 'Akkuschrauber der Marke Kestrel, Modell Neo', 1161.94, 194,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('A-00091', 'Zentra Soundbar Ultra', 'Soundbar der Marke Zentra, Modell Ultra', 1043.92, 0,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('B-00092', 'Wolkenstein Bürostuhl X', 'Bürostuhl der Marke Wolkenstein, Modell X', 1474.72, 194,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('W-00093', 'Kronos Winkelschleifer Eco', 'Winkelschleifer der Marke Kronos, Modell Eco', 530.50, 301,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('A-00094', 'Zentra Kopfhörer Pro', 'Kopfhörer der Marke Zentra, Modell Pro', 1348.17, 0,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('FV-00095', 'Adler Objektiv 2000', 'Objektiv der Marke Adler, Modell 2000', 1876.10, 304,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('E-00096', 'Bergmann LED-Panel Lite', 'LED-Panel der Marke Bergmann, Modell Lite', 1194.31, 405,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('W-00097', 'Falkon Lötkolben S', 'Lötkolben der Marke Falkon, Modell S', 1263.38, 188,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('E-00098', 'Vaillux Netzteil Neo', 'Netzteil der Marke Vaillux, Modell Neo', 371.21, 35,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('P-00099', 'Zentra Grafiktablett Air', 'Grafiktablett der Marke Zentra, Modell Air', 1492.57, 146,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('S-00100', 'Wolkenstein SSD NVMe X', 'SSD NVMe der Marke Wolkenstein, Modell X', 1102.53, 20,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('SH-00101', 'Adler Smart-Thermostat X', 'Smart-Thermostat der Marke Adler, Modell X', 508.08, 41,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('P-00102', 'Orbit Scanner Eco', 'Scanner der Marke Orbit, Modell Eco', 917.99, 442,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('E-00103', 'Wolkenstein Powerbank 4K', 'Powerbank der Marke Wolkenstein, Modell 4K', 602.71, 335,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('C-00104', 'Falkon Gehäuse Max', 'Gehäuse der Marke Falkon, Modell Max', 1720.10, 440,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('S-00105', 'Vaillux USB-Stick Max', 'USB-Stick der Marke Vaillux, Modell Max', 1670.64, 189,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('B-00106', 'Kestrel Laminiergerät Max', 'Laminiergerät der Marke Kestrel, Modell Max', 1562.53, 205,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('E-00107', 'Orbit LED-Panel Plus', 'LED-Panel der Marke Orbit, Modell Plus', 422.35, 70,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('E-00108', 'Zentra Spannungswandler Eco', 'Spannungswandler der Marke Zentra, Modell Eco', 1209.90, 186,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('P-00109', 'Aurus Dockingstation Pro', 'Dockingstation der Marke Aurus, Modell Pro', 1112.47, 257,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('E-00110', 'Adler LED-Panel Ultra', 'LED-Panel der Marke Adler, Modell Ultra', 1135.61, 197,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('S-00111', 'Adler RAM-Modul Compact', 'RAM-Modul der Marke Adler, Modell Compact', 506.83, 250,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('B-00112', 'Nordika Schreibtischlampe HD', 'Schreibtischlampe der Marke Nordika, Modell HD', 1650.19, 251,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('N-00113', 'Vaillux Access Point S', 'Access Point der Marke Vaillux, Modell S', 1559.54, 446,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('SH-00114', 'Adler Smart-Steckdose Neo', 'Smart-Steckdose der Marke Adler, Modell Neo', 1258.13, 478,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('P-00115', 'Adler Maus HD', 'Maus der Marke Adler, Modell HD', 193.66, 206,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('FV-00116', 'Nordika Gimbal Lite', 'Gimbal der Marke Nordika, Modell Lite', 444.93, 355,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('B-00117', 'Aurus Schreibtischlampe 2000', 'Schreibtischlampe der Marke Aurus, Modell 2000', 560.08, 483,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('B-00118', 'Aurus Monitor 27 4K', 'Monitor 27 der Marke Aurus, Modell 4K', 1017.82, 140,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('N-00119', 'Vaillux Router Neo', 'Router der Marke Vaillux, Modell Neo', 1052.60, 220,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('P-00120', 'Adler Dockingstation 4K', 'Dockingstation der Marke Adler, Modell 4K', 928.04, 97,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('N-00121', 'Falkon WLAN-Repeater Compact', 'WLAN-Repeater der Marke Falkon, Modell Compact', 314.87, 409,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00122', 'Bergmann Mixer Air', 'Mixer der Marke Bergmann, Modell Air', 1868.44, 400,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('E-00123', 'Nordika Spannungswandler Plus', 'Spannungswandler der Marke Nordika, Modell Plus', 679.49, 343,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('W-00124', 'Vaillux Bohrmaschine S', 'Bohrmaschine der Marke Vaillux, Modell S', 1672.63, 359,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('N-00125', 'Bergmann Netzwerkkabel Ultra', 'Netzwerkkabel der Marke Bergmann, Modell Ultra', 1657.20, 439,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('A-00126', 'Bergmann Kopfhörer Ultra', 'Kopfhörer der Marke Bergmann, Modell Ultra', 1708.91, 97,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('H-00127', 'Wolkenstein Kaffeemaschine X', 'Kaffeemaschine der Marke Wolkenstein, Modell X', 887.11, 131,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('G-00128', 'Wolkenstein Gaming-Tastatur X', 'Gaming-Tastatur der Marke Wolkenstein, Modell X', 930.99, 139,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('H-00129', 'Aurus Mixer Plus', 'Mixer der Marke Aurus, Modell Plus', 1015.19, 338,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('G-00130', 'Orbit Gaming-Tastatur 2000', 'Gaming-Tastatur der Marke Orbit, Modell 2000', 1421.43, 279,
        (SELECT id FROM categories WHERE name = 'Gaming'), (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('B-00131', 'Kestrel Aktenvernichter Plus', 'Aktenvernichter der Marke Kestrel, Modell Plus', 356.22, 26,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('G-00132', 'Kestrel Headset Lite', 'Headset der Marke Kestrel, Modell Lite', 1862.54, 273,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('N-00133', 'Nordika WLAN-Repeater Ultra', 'WLAN-Repeater der Marke Nordika, Modell Ultra', 54.38, 377,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('SH-00134', 'Orbit LED-Lampe S', 'LED-Lampe der Marke Orbit, Modell S', 954.14, 252,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('N-00135', 'Aurus Router Max', 'Router der Marke Aurus, Modell Max', 149.82, 452,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('G-00136', 'Nordika Gaming-Stuhl Pro', 'Gaming-Stuhl der Marke Nordika, Modell Pro', 499.59, 167,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Schwarzwald Komponenten GmbH')),
       ('A-00137', 'Vaillux Lautsprecher HD', 'Lautsprecher der Marke Vaillux, Modell HD', 1611.52, 368,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('C-00138', 'Vaillux Grafikkarte Eco', 'Grafikkarte der Marke Vaillux, Modell Eco', 1709.12, 231,
        (SELECT id FROM categories WHERE name = 'Computer'), (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('SH-00139', 'Zentra Bewegungsmelder Neo', 'Bewegungsmelder der Marke Zentra, Modell Neo', 83.60, 387,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('S-00140', 'Zentra USB-Stick Lite', 'USB-Stick der Marke Zentra, Modell Lite', 836.33, 278,
        (SELECT id FROM categories WHERE name = 'Speicher'), (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('S-00141', 'Vaillux Festplatte Air', 'Festplatte der Marke Vaillux, Modell Air', 1777.44, 4,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('B-00142', 'Zentra Monitor 27 X', 'Monitor 27 der Marke Zentra, Modell X', 690.11, 154,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('W-00143', 'Kestrel Bohrmaschine X', 'Bohrmaschine der Marke Kestrel, Modell X', 678.65, 132,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('A-00144', 'Orbit Bluetooth-Empfänger HD', 'Bluetooth-Empfänger der Marke Orbit, Modell HD', 1096.38, 367,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('S-00145', 'Kronos NAS-Gehäuse Eco', 'NAS-Gehäuse der Marke Kronos, Modell Eco', 1051.00, 218,
        (SELECT id FROM categories WHERE name = 'Speicher'), (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('G-00146', 'Falkon Gaming-Stuhl Eco', 'Gaming-Stuhl der Marke Falkon, Modell Eco', 625.73, 389,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Schwarzwald Komponenten GmbH')),
       ('S-00147', 'Adler SSD SATA 4K', 'SSD SATA der Marke Adler, Modell 4K', 601.78, 135,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('E-00148', 'Delphi LED-Panel Eco', 'LED-Panel der Marke Delphi, Modell Eco', 179.46, 24,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('C-00149', 'Adler Mainboard Eco', 'Mainboard der Marke Adler, Modell Eco', 1798.46, 84,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('W-00150', 'Delphi Werkzeugset Air', 'Werkzeugset der Marke Delphi, Modell Air', 462.07, 243,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('W-00151', 'Delphi Schlagbohrer Plus', 'Schlagbohrer der Marke Delphi, Modell Plus', 672.95, 232,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('N-00152', 'Falkon Netzwerkkabel S', 'Netzwerkkabel der Marke Falkon, Modell S', 308.62, 359,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('C-00153', 'Kronos Prozessor S', 'Prozessor der Marke Kronos, Modell S', 762.19, 343,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00154', 'Wolkenstein Wasserkocher HD', 'Wasserkocher der Marke Wolkenstein, Modell HD', 1725.03, 192,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('B-00155', 'Bergmann Whiteboard 2000', 'Whiteboard der Marke Bergmann, Modell 2000', 1453.44, 310,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('P-00156', 'Kronos Dockingstation 2000', 'Dockingstation der Marke Kronos, Modell 2000', 122.80, 160,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('SH-00157', 'Aurus LED-Lampe Max', 'LED-Lampe der Marke Aurus, Modell Max', 440.51, 345,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('A-00158', 'Kronos Audio-Interface Lite', 'Audio-Interface der Marke Kronos, Modell Lite', 1253.72, 145,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('N-00159', 'Zentra Modem Lite', 'Modem der Marke Zentra, Modell Lite', 1105.69, 135,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('S-00160', 'Delphi SSD SATA Plus', 'SSD SATA der Marke Delphi, Modell Plus', 1775.50, 104,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('FV-00161', 'Orbit Systemkamera Eco', 'Systemkamera der Marke Orbit, Modell Eco', 763.44, 75,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('S-00162', 'Bergmann Festplatte 2000', 'Festplatte der Marke Bergmann, Modell 2000', 410.68, 135,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('W-00163', 'Kronos Lötkolben Eco', 'Lötkolben der Marke Kronos, Modell Eco', 855.22, 8,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('C-00164', 'Bergmann Grafikkarte X', 'Grafikkarte der Marke Bergmann, Modell X', 432.52, 173,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('C-00165', 'Aurus Mini-PC Max', 'Mini-PC der Marke Aurus, Modell Max', 1764.89, 449,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('W-00166', 'Delphi Schlagbohrer Air', 'Schlagbohrer der Marke Delphi, Modell Air', 1312.94, 98,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('B-00167', 'Aurus Aktenvernichter Neo', 'Aktenvernichter der Marke Aurus, Modell Neo', 545.33, 245,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('P-00168', 'Aurus Grafiktablett Lite', 'Grafiktablett der Marke Aurus, Modell Lite', 724.33, 199,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'TechnoHaus GmbH')),
       ('SH-00169', 'Wolkenstein Bewegungsmelder Pro', 'Bewegungsmelder der Marke Wolkenstein, Modell Pro', 1898.19,
        344, (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('SH-00170', 'Kestrel LED-Lampe Max', 'LED-Lampe der Marke Kestrel, Modell Max', 1138.69, 455,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('H-00171', 'Kronos Wasserkocher Compact', 'Wasserkocher der Marke Kronos, Modell Compact', 1193.93, 52,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('E-00172', 'Bergmann Netzteil Compact', 'Netzteil der Marke Bergmann, Modell Compact', 447.82, 51,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('FV-00173', 'Bergmann Gimbal 4K', 'Gimbal der Marke Bergmann, Modell 4K', 547.95, 139,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('S-00174', 'Delphi SD-Karte S', 'SD-Karte der Marke Delphi, Modell S', 1769.92, 53,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('C-00175', 'Aurus Grafikkarte Neo', 'Grafikkarte der Marke Aurus, Modell Neo', 1055.24, 301,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('P-00176', 'Zentra Dockingstation X', 'Dockingstation der Marke Zentra, Modell X', 1839.81, 296,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('G-00177', 'Orbit Controller Neo', 'Controller der Marke Orbit, Modell Neo', 1075.05, 13,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('G-00178', 'Kronos Monitor 240Hz 2000', 'Monitor 240Hz der Marke Kronos, Modell 2000', 106.02, 487,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('E-00179', 'Wolkenstein Ladegerät HD', 'Ladegerät der Marke Wolkenstein, Modell HD', 331.21, 373,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('C-00180', 'Falkon Workstation Pro', 'Workstation der Marke Falkon, Modell Pro', 463.11, 290,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('A-00181', 'Delphi Audio-Interface HD', 'Audio-Interface der Marke Delphi, Modell HD', 1204.71, 171,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00182', 'Vaillux Toaster HD', 'Toaster der Marke Vaillux, Modell HD', 1693.91, 235,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('A-00183', 'Kronos Lautsprecher HD', 'Lautsprecher der Marke Kronos, Modell HD', 380.19, 220,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('SH-00184', 'Aurus Überwachungskamera Ultra', 'Überwachungskamera der Marke Aurus, Modell Ultra', 859.63, 304,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('C-00185', 'Bergmann Workstation Air', 'Workstation der Marke Bergmann, Modell Air', 1015.11, 64,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('B-00186', 'Kestrel Bürostuhl Eco', 'Bürostuhl der Marke Kestrel, Modell Eco', 569.94, 301,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('S-00187', 'Bergmann SSD SATA Ultra', 'SSD SATA der Marke Bergmann, Modell Ultra', 1250.92, 289,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('P-00188', 'Orbit Webcam Lite', 'Webcam der Marke Orbit, Modell Lite', 534.37, 127,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('W-00189', 'Zentra Schlagbohrer S', 'Schlagbohrer der Marke Zentra, Modell S', 483.03, 61,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('A-00190', 'Bergmann Lautsprecher HD', 'Lautsprecher der Marke Bergmann, Modell HD', 1749.14, 319,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('G-00191', 'Zentra Monitor 240Hz Compact', 'Monitor 240Hz der Marke Zentra, Modell Compact', 162.43, 9,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH')),
       ('A-00192', 'Aurus Bluetooth-Empfänger Pro', 'Bluetooth-Empfänger der Marke Aurus, Modell Pro', 470.62, 243,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('G-00193', 'Orbit Gaming-Stuhl S', 'Gaming-Stuhl der Marke Orbit, Modell S', 1429.93, 425,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Leipzig Netzwerk GmbH')),
       ('N-00194', 'Vaillux Switch X', 'Switch der Marke Vaillux, Modell X', 1297.63, 341,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Köln Media Systeme GmbH')),
       ('FV-00195', 'Bergmann Systemkamera Air', 'Systemkamera der Marke Bergmann, Modell Air', 811.66, 90,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('P-00196', 'Kestrel Maus Compact', 'Maus der Marke Kestrel, Modell Compact', 1386.55, 344,
        (SELECT id FROM categories WHERE name = 'Peripheriegeräte'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('E-00197', 'Orbit Multimeter HD', 'Multimeter der Marke Orbit, Modell HD', 875.42, 135,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('SH-00198', 'Adler Smart-Steckdose X', 'Smart-Steckdose der Marke Adler, Modell X', 1755.08, 403,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('A-00199', 'Adler Mikrofon 4K', 'Mikrofon der Marke Adler, Modell 4K', 1715.16, 315,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Nordlicht Systeme GmbH')),
       ('FV-00200', 'Kestrel Stativ Lite', 'Stativ der Marke Kestrel, Modell Lite', 1414.12, 243,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('H-00201', 'Kronos Staubsauger Max', 'Staubsauger der Marke Kronos, Modell Max', 1478.69, 83,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('E-00202', 'Zentra Netzteil Compact', 'Netzteil der Marke Zentra, Modell Compact', 1196.57, 453,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Frankfurt Hardware GmbH')),
       ('FV-00203', 'Adler Systemkamera 4K', 'Systemkamera der Marke Adler, Modell 4K', 17.99, 384,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('N-00204', 'Bergmann Firewall-Box Air', 'Firewall-Box der Marke Bergmann, Modell Air', 535.46, 328,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('W-00205', 'Kronos Schlagbohrer X', 'Schlagbohrer der Marke Kronos, Modell X', 604.36, 380,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Kiel Marine Electronics GmbH')),
       ('C-00206', 'Delphi Mini-PC Pro', 'Mini-PC der Marke Delphi, Modell Pro', 1140.40, 250,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Donau Distribution GmbH')),
       ('SH-00207', 'Kestrel Türklingel Max', 'Türklingel der Marke Kestrel, Modell Max', 894.04, 155,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('S-00208', 'Nordika SSD NVMe Pro', 'SSD NVMe der Marke Nordika, Modell Pro', 1824.81, 41,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('S-00209', 'Nordika SD-Karte S', 'SD-Karte der Marke Nordika, Modell S', 225.83, 54,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('E-00210', 'Kronos USB-Hub Max', 'USB-Hub der Marke Kronos, Modell Max', 1296.96, 274,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('A-00211', 'Orbit Mikrofon 4K', 'Mikrofon der Marke Orbit, Modell 4K', 566.73, 65,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('E-00212', 'Kronos Powerbank 2000', 'Powerbank der Marke Kronos, Modell 2000', 422.90, 166,
        (SELECT id FROM categories WHERE name = 'Elektronik'),
        (SELECT id FROM suppliers WHERE name = 'Sachsen Computer GmbH')),
       ('FV-00213', 'Delphi Ringlicht Eco', 'Ringlicht der Marke Delphi, Modell Eco', 1192.99, 140,
        (SELECT id FROM categories WHERE name = 'Foto & Video'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('W-00214', 'Kestrel Lötkolben 2000', 'Lötkolben der Marke Kestrel, Modell 2000', 1011.74, 217,
        (SELECT id FROM categories WHERE name = 'Werkzeuge'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('SH-00215', 'Nordika Bewegungsmelder Eco', 'Bewegungsmelder der Marke Nordika, Modell Eco', 989.12, 226,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Ruhr Digital GmbH')),
       ('N-00216', 'Adler Firewall-Box X', 'Firewall-Box der Marke Adler, Modell X', 761.20, 142,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00217', 'Zentra Staubsauger Max', 'Staubsauger der Marke Zentra, Modell Max', 1102.08, 475,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('S-00218', 'Kestrel Festplatte Neo', 'Festplatte der Marke Kestrel, Modell Neo', 1896.08, 51,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('A-00219', 'Zentra Bluetooth-Empfänger X', 'Bluetooth-Empfänger der Marke Zentra, Modell X', 1533.11, 75,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'München Digital GmbH')),
       ('H-00220', 'Orbit Toaster Compact', 'Toaster der Marke Orbit, Modell Compact', 934.72, 221,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('N-00221', 'Vaillux Modem Pro', 'Modem der Marke Vaillux, Modell Pro', 225.67, 496,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('S-00222', 'Zentra RAM-Modul Compact', 'RAM-Modul der Marke Zentra, Modell Compact', 103.59, 324,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('C-00223', 'Falkon Grafikkarte Pro', 'Grafikkarte der Marke Falkon, Modell Pro', 141.78, 323,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Hanse IT Distribution GmbH')),
       ('SH-00224', 'Zentra Smart-Steckdose 4K', 'Smart-Steckdose der Marke Zentra, Modell 4K', 1633.45, 36,
        (SELECT id FROM categories WHERE name = 'Smart Home'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('C-00225', 'Delphi Desktop-PC Max', 'Desktop-PC der Marke Delphi, Modell Max', 1654.09, 152,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('H-00226', 'Orbit Wasserkocher 4K', 'Wasserkocher der Marke Orbit, Modell 4K', 382.64, 303,
        (SELECT id FROM categories WHERE name = 'Haushaltsgeräte'),
        (SELECT id FROM suppliers WHERE name = 'Hamburger Speicher GmbH')),
       ('S-00227', 'Falkon RAM-Modul 4K', 'RAM-Modul der Marke Falkon, Modell 4K', 656.06, 351,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('S-00228', 'Zentra NAS-Gehäuse Pro', 'NAS-Gehäuse der Marke Zentra, Modell Pro', 14.21, 394,
        (SELECT id FROM categories WHERE name = 'Speicher'),
        (SELECT id FROM suppliers WHERE name = 'Stuttgart Präzision GmbH')),
       ('N-00229', 'Orbit Modem HD', 'Modem der Marke Orbit, Modell HD', 1863.34, 274,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'Elbe Logistik & Technik GmbH')),
       ('N-00230', 'Kronos Router Lite', 'Router der Marke Kronos, Modell Lite', 1039.48, 427,
        (SELECT id FROM categories WHERE name = 'Netzwerk'),
        (SELECT id FROM suppliers WHERE name = 'RheinTech Handels GmbH')),
       ('A-00231', 'Zentra Soundbar S', 'Soundbar der Marke Zentra, Modell S', 405.06, 402,
        (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('C-00232', 'Adler Laptop Plus', 'Laptop der Marke Adler, Modell Plus', 218.50, 222,
        (SELECT id FROM categories WHERE name = 'Computer'),
        (SELECT id FROM suppliers WHERE name = 'Westfalen Elektro GmbH')),
       ('A-00233', 'Bergmann Audio-Interface Compact', 'Audio-Interface der Marke Bergmann, Modell Compact', 1808.21,
        120, (SELECT id FROM categories WHERE name = 'Audio'),
        (SELECT id FROM suppliers WHERE name = 'Bavaria Tech Supply GmbH')),
       ('B-00234', 'Wolkenstein Laminiergerät HD', 'Laminiergerät der Marke Wolkenstein, Modell HD', 1305.92, 77,
        (SELECT id FROM categories WHERE name = 'Bürobedarf'),
        (SELECT id FROM suppliers WHERE name = 'Berliner Elektronik AG')),
       ('G-00235', 'Vaillux Monitor 240Hz X', 'Monitor 240Hz der Marke Vaillux, Modell X', 1237.25, 399,
        (SELECT id FROM categories WHERE name = 'Gaming'),
        (SELECT id FROM suppliers WHERE name = 'Alpen Peripherie GmbH'));

-- stock_movements (4000 registros generados aleatoriamente)
INSERT INTO stock_movements (type, quantity, date, product_id, warehouse_id)
SELECT CASE WHEN random() < 0.5 THEN 'IN' ELSE 'OUT' END,
       (floor(random() * 100) + 1)::int,
       timestamp '2025-01-01 00:00:00' + (random() * 730) * interval '1 day',
       prod.id,
       wh.id
FROM generate_series(1, 4000) AS movement
         CROSS JOIN LATERAL (SELECT id FROM products ORDER BY random() LIMIT 1) AS prod
         CROSS JOIN LATERAL (SELECT id FROM warehouses ORDER BY random() LIMIT 1) AS wh;

COMMIT;