spring.application.name=inventory-manager-api

# Hibernate detects dialect from PostgreSQL JDBC driver (DB_URL)
# so don't need to specify

spring.datasource.url=${DB_URL} 
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

